accounts/urls.py
from django.urls import path
from . import views

app_name='accounts'

urlpatterns = [
    path('login/',views.loginView,name='login'),
    path('logout/',views.logoutView,name='logout'),
    path('profile/',views.profileView,name='profile'),
    path('regsiter/',views.registerView,name='register'),
    path('edit_profile/',views.ProfileEditView,name='edit_profile'),
]

base/urls.py
from django.urls import path
from . import views

app_name = 'concert_app'
urlpatterns = [
    path('',views.home,name="home"),
    path('concert_list/',views.concertListView,name='concert_list'),
    path('location_list/',views.locationListView,name='location_list'),
    path('concert/<int:pk>',views.detailView,name='detail'),
    path('time_list/',views.timeListView,name='time_list'),
    path('concert_editing/<int:pk>',views.concertEditing,name='concert_editing'),
]

concert/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('base.urls')),
    path('accounts/',include('accounts.urls')),
]
# giving images url
if settings.DEBUG:
    urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

accounts/models.py
from email.policy import default
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class profileModel(models.Model):
    class Meta:
        verbose_name = 'کنسرت'
        verbose_name_plural = 'پروفایل ها'

    user = models.OneToOneField(User,on_delete=models.CASCADE,verbose_name='کاربری',related_name='profile')

    # we comment name and surname because django user in admin panel has this features
    # name = models.CharField(max_length=200)
    # surname = models.CharField(max_length=200)

    profile_img = models.ImageField(upload_to = 'profileImages/',null=True,verbose_name='عکس پروفایل',default='defaultImagesProfile/download.png')
    status_choices = [
        ('Man','مرد'),
        ('Woman','زن'),
    ]
    gender = models.CharField(choices=status_choices,max_length=10)

    credit = models.IntegerField(verbose_name='اعتبار',default=0)

    def __str__(self):
        return f"{self.user.first_name} {self.user.last_name}"

        

accounts/forms.py
from django.contrib.auth.forms import UserChangeForm
from django import forms
from .models import profileModel

class ProfileRegisterationForm(forms.ModelForm):
    # django user elements
    first_name = forms.CharField(max_length=100)
    last_name = forms.CharField(max_length=100)
    username = forms.CharField(max_length=100)
    password = forms.CharField(widget=forms.PasswordInput)
    email = forms.CharField(widget=forms.EmailInput)

    # profile elements
    class Meta:
        model = profileModel
        fields = ['credit',"profile_img","gender"]

class ProfileEditForm(forms.ModelForm):
    class Meta:
        model = profileModel
        fields = ['profile_img','credit','gender']

# changing djnago user
class UserEditForm(UserChangeForm):
    class Meta(UserChangeForm.Meta):
        fields = ['first_name','last_name','email']
    

accounts/views.py
from django.shortcuts import render,redirect
from django.contrib.auth import authenticate,login,logout
from django.contrib import messages
from django.conf import settings
from django.contrib.auth.decorators import login_required

from accounts.models import profileModel
from .forms import *
from django.contrib.auth.models import User
# Create your views here.

def loginView(request):
    if request.method=='POST':
        username = request.POST.get('loginName')
        password = request.POST.get('loginPassword')

        # Authenticating username and password
        user = authenticate(request,username=username,password=password)
        
        # if it is successful it returns name of the user
        if user is not None:
            login(request,user)

            # user will be redirected to the requested page
            if request.GET.get('next'):
                return redirect(request.GET.get('next'))

            # if url doesn't have 'next' parameter
            return redirect(settings.LOGIN_REDIRECT_URL)
        else:
            messages.info(request,"نام کاربری یا رمز ورود اشتباه است")

    return render(request,'accounts/login.html',context={})

def logoutView(request):
    logout(request)
    return redirect('concert_app:concert_list')

@login_required
def profileView(request):
    profile = request.user.profile
    context = {
        'profile':profile
    }
    return render(request,'accounts/profile.html',context)

def registerView(request):
    RegisterForm = ProfileRegisterationForm()
    if request.method == 'POST':
        RegisterForm = ProfileRegisterationForm(request.POST,request.FILES)
        if RegisterForm.is_valid():
            # first we should create a user for registeration
            user = User.objects.create_user(
                first_name = RegisterForm.cleaned_data['first_name'],
                last_name = RegisterForm.cleaned_data['last_name'],
                email = RegisterForm.cleaned_data['email'],
                password = RegisterForm.cleaned_data['password'],
                username = RegisterForm.cleaned_data['username'],
            )
            user.save()

            # then we should make a profile for this user
            # we make an instance for profile
            profiel_model = profileModel(
                    user = user,
                    gender = RegisterForm.cleaned_data['gender'],
                    profile_img = RegisterForm.cleaned_data['profile_img'],
                    credit = RegisterForm.cleaned_data['credit'],
                )
            # saving instance model
            profiel_model.save()
            return redirect('accounts:login')

    context = {
        'RegisterForm':RegisterForm
    }
    return render(request,'accounts/register.html',context)

def ProfileEditView(request):
    if request.method == 'POST':
        profileEditForm = ProfileEditForm(request.POST,request.FILES,instance=request.user.profile)
        userEditForm = UserEditForm(request.POST,instance=request.user)
        if profileEditForm.is_valid() and userEditForm.is_valid():
            profileEditForm.save()
            userEditForm.save()
            return redirect('accounts:profile')
    else:
        profileEditForm = ProfileEditForm(instance=request.user.profile)
        userEditForm = UserEditForm(instance=request.user)
    context = {
        'profileEditForm':profileEditForm,
        'profileImg':request.user.profile.profile_img,
        'userEditForm':userEditForm
    }
    return render(request,'accounts/profile_edit.html',context)

accounts/templates/accounts/login.html
{% extends 'base/layout.html' %}

{% block title %}
{{concert.name}}
{% endblock %}

{% block titlepage %}
ورود کاربران
{% endblock %}

{% block mainContent %}

<!-- Pills navs -->
<ul class="nav nav-pills nav-justified mb-3" id="ex1" role="tablist">
    <li class="nav-item" role="presentation">
      <a class="nav-link active" id="tab-login" data-mdb-toggle="pill" href="#pills-login" role="tab"
        aria-controls="pills-login" aria-selected="true">ورود</a>
    </li>
    <li class="nav-item" role="presentation">
      <a class="nav-link" id="tab-register" data-mdb-toggle="pill" href="{% url 'accounts:register' %}" role="tab"
        aria-controls="pills-register" aria-selected="false">ثبت نام</a>
    </li>
  </ul>
  <!-- Pills navs -->
  
  <!-- Pills content -->
  <div class="tab-content">
    <div class="tab-pane fade show active" id="pills-login" role="tabpanel" aria-labelledby="tab-login">
      <form action="" method="post">
        {% csrf_token %}
        <!-- Email input -->
        <div class="form-outline mb-4">
          <input type="text" name="loginName" id="loginName" class="form-control" />
          <label class="form-label" for="loginName"> نام کاربری</label>
        </div>
  
        <!-- Password input -->
        <div class="form-outline mb-4">
          <input type="password" name="loginPassword" id="loginPassword" class="form-control" />
          <label class="form-label" for="loginPassword">رمز</label>
        </div>
        <div>
            <p style="color: red;">
                {% for message in messages %}
                {{message}}
                {% endfor %}
            </p>
        </div>
        <!-- 2 column grid layout -->
        <div class="row mb-4">
          <div class="col-md-6 d-flex justify-content-center">
            <!-- Checkbox -->
            <div class="form-check mb-3 mb-md-0">
              <input class="form-check-input" type="checkbox" value="" id="loginCheck" checked />
              <label class="form-check-label" for="loginCheck"> مرا به خاطر بسپار </label>
            </div>
          </div>
  
          <div class="col-md-6 d-flex justify-content-center">
            <!-- Simple link -->
            <a href="#!">رمز را فراموش کردم؟</a>
          </div>
        </div>
  
        <!-- Submit button -->
        <button type="submit" class="btn btn-primary btn-block mb-4">ورود</button>
  
        <!-- Register buttons -->
        <div class="text-center">
          <p>هنوز ثبت نام نکردم? <a href="{% url 'accounts:register' %}">ثبت نام</a></p>
        </div>
      </form>
    </div>
    

{% endblock %}

accounts/templates/accounts/profile.html
{% extends 'base/layout.html' %}
{% load static %}

{% block title %} Profile {% endblock %}

{% block titlepage %}
پروفایل 
{% endblock %}

{% block mainContent %}
    <div class="row">
        <div class="col-md-8">
            <p>نام و نام خانوادگی: {{profile.user.get_full_name}}</p>
            <p>ایمیل: {{profile.user.email}}</p>
            <p>جنسیت: {{profile.get_gender_display}}</p>
            <p>مقدار اعتبار: {{profile.credit}} </p>
        </div>
        <div class="col-md-4">
            <img src="{{profile.profile_img.url}}">
        </div>
    </div>
    <div>
        <a href="{% url 'accounts:edit_profile' %}">ویرایش پروفایل</a>
    </div>
{% endblock %}

accounts/templates/accounts/profile_edit.html
{% extends 'base/layout.html' %}
{% load static %}

{% block title %} Profile {% endblock %}

{% block titlepage %}
ویرایش پروفایل 
{% endblock %}

{% block mainContent %}
<form action="" method="post">
    {% csrf_token %}
    <div class="row">
        <div class="col-md-8">
            <p>نام: {{userEditForm.first_name}}</p>
            <p>نام خانوادگی:{{userEditForm.last_name}} </p>
            <p>ایمیل: {{userEditForm.email}} </p>
            <p>جنسیت: {{profileEditForm.gender}}</p>
            <p>مقدار اعتبار: {{profileEditForm.credit}} </p>
        </div>
        <div class="col-md-4">
            <img src="{{profileImg.url}}">
            {{profileEditForm.profile_img}}
        </div>
        <button class="btn btn-sm-success" type="submit">ویرایش</button>
    </div>
</form>
<!-- {{userEditForm}} -->
{% endblock %}

accounts/templates/accounts/register.html
{% extends 'base/layout.html' %}
{% load static %}

{% block title %} ConcertList {% endblock %}

{% block titlepage %}
 ثبت نام
{% endblock %}

{% block mainContent %}
<ul class="nav nav-pills nav-justified mb-3" id="ex1" role="tablist">
  <li class="nav-item" role="presentation">
    <a class="nav-link active" id="tab-login" data-mdb-toggle="pill" href="{% url 'accounts:login' %}" role="tab"
      aria-controls="pills-login" aria-selected="true">ورود</a>
  </li>
  <li class="nav-item" role="presentation">
    <a class="nav-link" id="tab-register" data-mdb-toggle="pill" href="{% url 'accounts:register' %}" role="tab"
      aria-controls="pills-register" aria-selected="false">ثبت نام</a>
  </li>
</ul>
<form action="" method="post" enctype="multipart/form-data">
  {% csrf_token %}
  <div class="mainborder">
    <div class="row">
      <div class='col-md-6'>
        <p>نام: {{RegisterForm.first_name}}</p>
        <p>نام خانوادگی: {{RegisterForm.last_name}}</p>
        <p>جنسیت: {{RegisterForm.gender}}</p>
        <p>اعتبار: {{RegisterForm.credit}}</p>
      </div>
      <div class='col-md-6'>
        <p>ایمیل: {{RegisterForm.email}}</p>
        <p>نام کاربری:  {{RegisterForm.username}}</p>
        <p>رمز: {{RegisterForm.password}}</p>
        {{RegisterForm.profile_img}}
      </div>
    </div>
  </div>
  <button type="submit">تایید</button>
</form>
{% endblock %}