accounts/urls.py
from django.urls import path
from . import views

app_name='accounts'

urlpatterns = [
    path('login/',views.loginView,name='login'),
    path('logout/',views.logoutView,name='logout'),
    path('profile/',views.profileView,name='profile'),
    path('regsiter/',views.registerView,name='register'),
    path('edit_profile/',views.ProfileEditView,name='edit_profile'),
]

base/urls.py
from django.urls import path
from . import views

app_name = 'concert_app'
urlpatterns = [
    path('',views.home,name="home"),
    path('concert_list/',views.concertListView,name='concert_list'),
    path('location_list/',views.locationListView,name='location_list'),
    path('concert/<int:pk>',views.detailView,name='detail'),
    path('time_list/',views.timeListView,name='time_list'),
    path('concert_editing/<int:pk>',views.concertEditing,name='concert_editing'),
]

concert/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('base.urls')),
    path('accounts/',include('accounts.urls')),
]
# giving images url
if settings.DEBUG:
    urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

base/models.py
from django.db import models
from jalali_date import datetime2jalali
from accounts.models import profileModel
# Create your models here.
class concertModel(models.Model):
    class Meta:
        verbose_name = 'کنسرت'
        verbose_name_plural = 'کنسرت ها'
    name = models.CharField(max_length=100,verbose_name='نام کنسرت')
    singer = models.CharField(max_length=100,verbose_name='نام خواننده')
    length = models.IntegerField(verbose_name='مدت زمان')
    poster = models.ImageField(upload_to = 'concertImages/',null=True,verbose_name='پوستر')

    def __str__(self):
        return self.singer

class locationModel(models.Model):
    class Meta:
        verbose_name = 'موقعیت'
        verbose_name_plural = 'موقعیت ها'
    name = models.CharField(max_length=100,verbose_name=' مکان')
    address = models.CharField(max_length=500,default='تهران-برج میلاد',verbose_name='آدرس')
    phone = models.CharField(max_length=11,null=True,verbose_name='تلفن')
    capacity = models.IntegerField(verbose_name='ظرفیت')

    def __str__(self):
        return self.name

class timeModel(models.Model):
    class Meta:
        verbose_name = 'زمان'
        verbose_name_plural = 'زمان ها'
    concert = models.ForeignKey("concertModel",on_delete=models.PROTECT,verbose_name='نام کنسرت')
    location = models.ForeignKey("locationModel",on_delete=models.PROTECT,verbose_name='موقعیت ')
    startdate = models.DateTimeField(verbose_name='تاریخ شروع ')
    seats = models.IntegerField(verbose_name=' صندلی باقی مانده')

    status_choices = (
        ('Start','فروش بلیط شروع شده است'),
        ('End','فروش بلیط تمام شده است'),
        ('Cancle','فروش بلیط کنسل شده است'),
        ('Sales','درحال فروش بلیط'),
    )
    status = models.CharField(choices=status_choices,max_length=200,verbose_name='وضعیت ')

    def __str__(self):
        return f" شروع:{self.startdate}| کنسرت :{self.concert.name}| سالن: {self.location.name}"

    # method for converting date to jalali date
    def get_jalali_date(self):
        return datetime2jalali(self.startdate)


class ticketModel(models.Model):
    class Meta:
        verbose_name = 'بلیت'
        verbose_name_plural = 'بلیت ها'
    profile = models.ForeignKey(profileModel,on_delete=models.PROTECT,verbose_name='پروفایل')
    time = models.ForeignKey('timeModel',on_delete=models.PROTECT,verbose_name='زمان ')
    ticket_img = models.ImageField(upload_to='ticketImages/',null=True,verbose_name='عکس')
    name = models.CharField(max_length=200,verbose_name='نام بلیت')
    price = models.IntegerField(verbose_name='قیمت ')

    def __str__(self):
        return f"TicketInfo : Profile :{self.profile.__str__()} ConcerInfo:{self.time.__str__()}"

base/forms.py
from django import forms
from .models import concertModel

class SearchForm(forms.Form):
    ConcertName = forms.CharField(max_length=200,label='نام کنسرت',required=False)

class ConcertForm(forms.ModelForm):
    class Meta:
        model = concertModel
        fields = '__all__'

base/views.py
from django.shortcuts import render,redirect
from .models import *
from django.contrib.auth.decorators import login_required
from .forms import *
# Create your views here.


def home(request):
    context={}
    return render(request,"base/home.html",context)

@login_required
def concertListView(request):
    searchForm = SearchForm(request.GET)
    if searchForm.is_valid():
        # print(searchForm.cleaned_data['searchText'])
        data = searchForm.cleaned_data['ConcertName']
        concerts = concertModel.objects.filter(name__contains=data)
    else:
        concerts = concertModel.objects.all()
    context={
        'searchForm':searchForm,
        'concerts':concerts,
        'concerts_count':concerts.count()
    }
    return render(request,'base/concertList.html',context)

@login_required
def locationListView(request):
    locations = locationModel.objects.all()
    context = {
        'locations':locations,
    }
    return render(request,'base/locationList.html',context)

@login_required
def detailView(request,pk):
    concert = concertModel.objects.get(id=pk)
    context = {
        'concert':concert
    }
    return render(request,'base/detail.html',context)

@login_required
def timeListView(request):
    # request is included the user 
    '''
    for authenticating we should check two elements
    1- user.is_authenticated
    2- user.is_active
    '''
    # if request.user.is_authenticated and request.user.is_active:
    times = timeModel.objects.all()
    context = {
        'times':times
    }
    return render(request,'base/timeList.html',context)

@login_required
def concertEditing(request,pk):
    concert = concertModel.objects.get(id=pk)
    if request.method == 'POST':
        concertForm = ConcertForm(request.POST,request.FILES,instance=concert)
        if concertForm.is_valid():
            concertForm.save()
            return redirect('concert_app:concert_list')
    concertForm = ConcertForm(instance=concert)
    context = {
        'concertForm':concertForm,
        'posterImage':concert.poster
    }
    return render(request,'base/concertEditing.html',context)
        

base/templates/base/concertEditing.html
{% extends 'base/layout.html' %}

{% block title %}

{% endblock %}

{% block titlepage %}
جزییات کنسرت 
{% endblock %}

{% block mainContent %}
    <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="mainborder">
            <div class="row">
                <div class="col-md-6">
                    <p>نام کنسرت: {{concertForm.name}}</p>
                    <p>نام خواننده : {{concertForm.singer}}</p>
                    <p>مدت زمان  :  {{concertForm.length}}</p>
                </div>
                <div class="col-md-6">
                    <div class="imageBox">
                        <img src="{{posterImage.url}}" >
                    </div>
                    {{concertForm.poster}}
                </div>
            </div>
        </div>
        <div class="buttonborder">
            <button type="submit" class="btn btn-success">ذخیره</button>
        </div>
    
    </form>
{% endblock %}

base/templates/base/concertList.html
{% extends 'base/layout.html' %}
{% load static %}

{% block title %} ConcertList {% endblock %}

{% block titlepage %}
 لیست کنسرت ها
{% endblock %}

{% block mainContent %}
{% if concerts %} 
    <form action="" method="get">
        {{searchForm}}
        <button type="submit" class="btn btn-success">جستجو</button>
    </form>
    {% for concert in concerts %}
        <div class="col-md-4">
            <a href="{% url 'concert_app:detail' concert.id%}">
                <div class="imageBox">
                    <img src="{{ concert.poster.url }}" alt="" />
                    {{concert}}
                </div>
            </a>
        </div>
    {% endfor %} 
{% endif %}
{% endblock %}

base/templates/base/detail.html
{% extends 'base/layout.html' %}

{% block title %}
{{concert.name}}
{% endblock %}

{% block titlepage %}
جزییات کنسرت {{concert.name}}
{% endblock %}

{% block mainContent %}
<div class="col-md-10">
    <h3>نام کنسرت : {{concert.name}}</h3>
    <h3>خواننده : {{concert.singer}}</h3>
    <h3>مدت زمان کنسرت : {{concert.length}}</h3>
</div>
<div class="col-md-2">
    <div class="imageBox">
        <img src="{{ concert.poster.url }}">
    </div>
</div>
<a href="{% url 'concert_app:concert_editing' concert.id %}">ویرایش پروفایل</a>
{% endblock %}

base/templates/base/home.html
{% extends "base/layout.html" %}

base/templates/base/layout.html
{% load static %}
<!DOCTYPE html>
<html dir="rtl">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <link rel="stylesheet" href="{% static 'css/bootstrap.rtl.css' %}" />
    <link rel="stylesheet" href="{% static 'css/fontawesome.min.css' %}" />
    <link rel="stylesheet" href="{% static 'css/style.css' %}" />

    <title>{% block title %}{% endblock %}</title>
  </head>
  <body>
    <div class="container">
        <div class="row box">
            <h1>{% block titlepage %}{% endblock %}</h1>
            <ul class="btnul">
                {% if user.is_authenticated %}
                  <li><a class="btn btn-danger" href="{% url 'accounts:logout' %}">خروج</a></li>
                  <li><a class="btn btn-success" href="{% url 'accounts:profile' %}">پروفایل</a></li>
                {% else %}
                  <li><a class="btn btn-success" href="{% url 'accounts:login' %}">ورود</a></li>
                {% endif %}
                <li><a class="btn btn-primary" href="{% url 'concert_app:concert_list' %}">صفحه اصلی</a></li>
                <li><a class="btn btn-primary" href="{% url 'concert_app:location_list' %}">اطلاعات محل</a></li>
                <li><a class="btn btn-primary" href="{% url 'concert_app:time_list' %}">لیست سانس ها</a></li>
            </ul>
          </div>

      <div class="row">
        {% block mainContent %}{% endblock %}
      </div>
    </div>
  </body>

base/templates/base/locationList.html
{% extends 'base/layout.html' %}

{% block title %} LocationList {% endblock %}

{% block titlepage %}
    لیست موقعیت ها
{% endblock %}

{% block mainContent %}
    {% if locations %} 
        <div class="row location">
            <div class="col-md-3">
                <h3>سالن</h3>
            </div>
            <div class="col-md-9">
                <h3>آدرس</h3>
            </div>
        </div>
        {% for location in locations %}
            <div class="row location">
                <div class="col-md-3">
                    {{location}}
                </div>
                <div class="col-md-9">
                    {{location.address}}
                </div>
            </div>
        {% endfor %} 
    {% endif %}
{% endblock %}

base/templates/base/timeList.html
{% extends 'base/layout.html' %}

{% block title %} TimeList {% endblock %}

{% block titlepage %}
لیست سانس ها
{% endblock %}

{% block mainContent %}
{% if times %} 
    {% for time in times %}
        <div class="col-md-4">
            <a>
                <div class="timeBox">
                    <h2>{{time.concert.name}}</h2>
                    <p>{{time.concert.singer}}</p>
                    <p>{{time.location.name}}</p>
                    <p>{{time.get_jalali_date}}</p>
                    <div 
                    class="
                    {% if time.status == 'Start' %}
                        btn btn-success
                    {% elif time.status == 'End' %}
                        btn btn-danger
                    {% elif time.status == 'Sales' %}
                        btn btn-primary
                    {% elif time.status == 'Cancle' %}
                        btn default

                    {% endif %}
                    ">
                        {{time.get_status_display}}
                    </div>
                </div>
            </a>
        </div>
    {% endfor %} 
{% endif %}
{% endblock %}